# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20171029_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
