# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0008_resort_transfer'),
        ('offers', '0005_offer_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='destination',
        ),
        migrations.AddField(
            model_name='offer',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resort.Resort'),
        ),
    ]
