# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_auto_20171024_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='image',
        ),
        migrations.AddField(
            model_name='resortimage',
            name='resort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resort.Resort'),
            preserve_default=False,
        ),
    ]
