# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0005_auto_20171029_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('villa_view', models.TextField(blank=True, null=True)),
                ('max_occupancy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experience/')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='VillaSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('villa_view', models.TextField(blank=True, null=True)),
                ('max_occupancy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillaSuiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='villas/')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.VillaSuite')),
            ],
        ),
        migrations.CreateModel(
            name='Wellness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('villa_view', models.TextField(blank=True, null=True)),
                ('max_occupancy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellnessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wellness/')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.Wellness')),
            ],
        ),
        migrations.CreateModel(
            name='WineDine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('villa_view', models.TextField(blank=True, null=True)),
                ('max_occupancy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WineDineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='winedine/')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.WineDine')),
            ],
        ),
        migrations.AddField(
            model_name='resort',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winedine',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.Resort'),
        ),
        migrations.AddField(
            model_name='wellness',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.Resort'),
        ),
        migrations.AddField(
            model_name='villasuite',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.Resort'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.Resort'),
        ),
    ]
