# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0006_auto_20171108_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='transfer_time',
            field=models.IntegerField(blank=True, help_text='eg: 25 minutes', null=True),
        ),
    ]
