# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0007_resort_transfer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='transfer',
            field=models.IntegerField(choices=[(0, 'Seaplane'), (1, 'Speedboat'), (2, 'Domestic Flight')], default=0),
        ),
    ]
