# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('from_email', models.EmailField(default='no-reply@amasing-asia.com', max_length=254)),
                ('reply_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
