# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('residence', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('arrival_date', models.DateField()),
                ('num_of_nights', models.IntegerField()),
                ('num_adults', models.IntegerField()),
                ('num_children', models.IntegerField()),
                ('num_infants', models.IntegerField()),
            ],
        ),
    ]
